version: '3'

networks:
    geolocation-network:
        driver: bridge
volumes:
    mongodb-volume:
    elastic_data: {}

services:
    zoo1:
        image: confluentinc/cp-zookeeper:7.3.0
        container_name: zoo1
        hostname: zoo1
        ports:
          - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT : 2181
            ZOOKEEPER_TICK_TIME : 2000
        networks:
          - geolocation-network
    kafka_geolocation:
        image: confluentinc/cp-kafka:7.3.0
        container_name: kafka_geolocation
        hostname: kafka_geolocation
        ports:
          - "9092:9092"
        depends_on: 
          - zoo1
        environment:
            KAFKA_BROKER_ID : 1
            KAFKA_ZOOKEEPER_CONNECT : 'zoo1:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka_geolocation:29092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR : 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR : 1
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka_geolocation:29092
            CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zoo1:2181
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
            CONFLUENT_METRICS_ENABLE: 'true'
            CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
        networks:
          - geolocation-network
    
    mongodb:
        image: mongo
        container_name: geolocation_mongodb
        ports:
          - "27018:27017"
        environment:
          MONGO_INITDB_DATABASE: users
          MONGO_INITDB_ROOT_USERNAME : root
          MONGO_INITDB_ROOT_PASSWORD : root
        volumes:
          - mongodb-volume:/data/db
        networks:
          - geolocation-network
        command: --bind_ip 0.0.0.0
    elasticsearch:
      image: elasticsearch:7.16.2
      container_name: elasticsearch
      restart: always
      volumes:
        - elastic_data:/usr/share/elasticsearch/data/
      environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        discovery.type: single-node
        ELASTIC_USERNAME : elastic
        ELASTIC_PASSWORD : elastic
      ports:
        - '9200:9200'
        - '9300:9300'
      networks:
        - geolocation-network

    Logstash:
      image: logstash:7.16.2
      container_name: logstash
      restart: always
      volumes:
        - ./logstash/:/logstash_dir
      command: logstash -f /logstash_dir/logstash.conf
      depends_on:
        - elasticsearch
      ports:
        - '9600:9600'
      environment:
        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
        - geolocation-network

    Kibana:
      image: kibana:7.16.2
      container_name: kibana
      restart: always
      ports:
        - '5601:5601'
      environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
        - ELASTIC_USERNAME=elastic
        - ELASTIC_PASSWORD=elastic
      depends_on:
        - elasticsearch
      networks:
        - geolocation-network
        

