version: '3'

networks:
    geolocation-network:
        driver: bridge
volumes:
    mongodb-volume:
    elastic_data: {}

services:
    zoo1:
        image: confluentinc/cp-zookeeper:7.3.0
        container_name: zoo1
        hostname: zoo1
        ports:
          - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT : 2181
            ZOOKEEPER_TICK_TIME : 2000
        networks:
          - geolocation-network
    kafka_geolocation:
        image: confluentinc/cp-kafka:7.3.0
        container_name: kafka_geolocation
        hostname: kafka_geolocation
        ports:
          - "9092:9092"
        depends_on: 
          - zoo1
        environment:
            KAFKA_BROKER_ID : 1
            KAFKA_ZOOKEEPER_CONNECT : 'zoo1:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka_geolocation:29092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR : 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR : 1
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka_geolocation:29092
            CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zoo1:2181
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
            CONFLUENT_METRICS_ENABLE: 'true'
            CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
        networks:
          - geolocation-network
    kafka-schema-registry:
        image: confluentinc/cp-schema-registry
        container_name: kafka-schema-registry
        hostname: kafka-schema-registry
        ports:
          - "8081:8081"
        environment:
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka_geolocation:29092
            SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
            SCHEMA_REGISTRY_LISTENERS : http://0.0.0.0:8081
        depends_on:
          - zoo1
          - kafka_geolocation
        networks:
          - geolocation-network
    kafka-connect:
        image: confluentinc/cp-kafka-connect
        container_name : kafka-connect
        networks:
          - geolocation-network
        ports :
          - "8083:8083"
        volumes:
          - ./connect-plugins:/connect-plugins
          - ./elasticsearch-sink.json:/etc/kafka-connect-elasticsearch/elasticsearch-sink.json
        environment :
            CONNECT_BOOTSTRAP_SERVERS: "kafka_geolocation:29092"
            CONNECT_GROUP_ID: compose-connect-group
            CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect-01"
            CONNECT_REST_PORT: 8083
            CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
            CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
            CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
            CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
            CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://kafka-schema-registry:8081'
            CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
            CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://kafka-schema-registry:8081'
            CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
            CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
            CONNECT_ZOOKEEPER_CONNECT: 'zoo1:2181'
        depends_on:
          - zoo1
          - kafka_geolocation
          - kafka-schema-registry
          - elasticsearch

            
    rest-proxy:
      image: confluentinc/cp-kafka-rest
      depends_on:
        - zoo1
        - kafka_geolocation
        - kafka-schema-registry
      ports:
        - "8082:8082"
      networks:
        - geolocation-network
      hostname: rest-proxy
      container_name: rest-proxy
      environment:
        KAFKA_REST_HOST_NAME : rest-proxy
        KAFKA_REST_BOOTSTRAP_SERVERS : PLAINTEXT://kafka_geolocation:29092
        KAFKA_REST_LISTENERS: http://0.0.0.0:8082
        KAFKA_REST_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081
    mongodb:
        image: mongo
        container_name: geolocation_mongodb
        ports:
          - "27018:27017"
        environment:
          MONGO_INITDB_DATABASE: users
          MONGO_INITDB_ROOT_USERNAME : root
          MONGO_INITDB_ROOT_PASSWORD : root
        volumes:
          - mongodb-volume:/data/db
        networks:
          - geolocation-network
        command: --bind_ip 0.0.0.0
    elasticsearch:
      image: elasticsearch:7.16.2
      container_name: elasticsearch
      restart: always
      volumes:
        - elastic_data:/usr/share/elasticsearch/data/
      environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        discovery.type: single-node
        ELASTIC_USERNAME : elastic
        ELASTIC_PASSWORD : elastic
      ports:
        - '9200:9200'
        - '9300:9300'
      networks:
        - geolocation-network

    Logstash:
      image: logstash:7.16.2
      container_name: logstash
      restart: always
      volumes:
        - ./logstash/:/logstash_dir
      command: logstash -f /logstash_dir/logstash.conf
      depends_on:
        - elasticsearch
      ports:
        - '9600:9600'
      environment:
        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
        - geolocation-network

    Kibana:
      image: kibana:7.16.2
      container_name: kibana
      restart: always
      ports:
        - '5601:5601'
      environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
        - ELASTIC_USERNAME=elastic
        - ELASTIC_PASSWORD=elastic
      depends_on:
        - elasticsearch
      networks:
        - geolocation-network
        

